### ISSUE TITLE
As a user I can see my results for the first quiz

### ISSUE THREAD

**Issue by m4v15** [FACK1/GBMQ#5]
- Overall score (x/20, %)
- comparison between people in the same postcode? Age?

**Comment by m4v15** [comment]
@djbritton can you think about the scoring for questions with multiple answers?

**Comment by m4v15** [comment]
- add intro about free training/materials

**Comment by Djbritton** [comment]
> @Djbritton can you think about the scoring for questions with multiple answers?

@mhmdtshref For the sake of simplicity it would be better if there was just 1 correct answer. All questions equally weighted. If I have included a question with more than 1 answer then apply half marks if partially correct
