### ISSUE TITLE
As a user I can do the training activities after the 1st quiz

### ISSUE THREAD

**Issue by m4v15** [FACK1/GBMQ#6]
Could do new material each day for 5 days

or

material + activity for one day

**Comment by m4v15** [comment]
Can rewatch old videos in the following days

**Comment by m4v15** [comment]
@djbritton could you send us some materials and potential activities

**Comment by m4v15** [comment]
possibly notifications @mhmdtshref @ameentalahmeh @RazanTayyem

**Comment by Djbritton** [comment]
> @Djbritton could you send us some materials and potential activities

I have attached an idea for a drag and drop activity. Ranking the cost of borrowing. Hopefully it makes sense but please feel free to ask
[drag and drop activity.docx](https://github.com/FACK1/GBMQ/files/2965689/drag.and.drop.activity.docx)
