### ISSUE TITLE
As a admin I can see general statistics

### ISSUE THREAD

**Issue by m4v15** [FACK1/GBMQ#9]
- overall user trends
- [ ] number of people taking the quiz
- [ ] average score
  - per age
  - per gender
  - per postcode
- english first language filter

**Comment by m4v15** [comment]
@djbritton can you add any other statistics you might like ( we can't promise we can do them all! 😄 )

**Comment by m4v15** [comment]
@mhmdtshref @ameentalahmeh @RazanTayyem I thought about this and you could use airtable as your backend/database - they have a good api and then you wouldn't need to create all of the admin user interface, as it would already exist on airtable

**Comment by Djbritton** [comment]
The other key data I would like (in addition to the above) is 
Comparison of 2nd quiz vs 1st quiz scores
- per age
- per gender
- per postcode
- per days training  (i.e. can I see whether quiz scores goes up in those users who access the training content vs those who don't)
